server.port=8081
logging.level.org.liquibase=DEBUG

# Primary Data Source
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bookdb
spring.datasource.username=bookuser
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update

# Disable Spring Boot's automatic schema.sql / data.sql runner
#spring.sql.init.mode=always

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.user=bookadmin
spring.liquibase.password=password
spring.liquibase.change-log=classpath:db/changelog-master.xml