spring.application.name=sdjpa-intro
#spring.jpa.show-sql=true

#Show SQL
spring.jpa.properties.hibernate.show_sql = true

#Format SQL
spring.jpa.properties.hibernate.format_sql = true

#Printing Parameter values - If Spring boot 3.0.2+
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#H2 Console
#You can access http://localhost:8080/h2-console/login.do?jsessionid=684e6995249c379306ce4222d95d027d
#then you put JDBC con string from your console
spring.h2.console.enabled=true

#H2 starts with MYSQL mode  - It acceps MYSQL Queries. Then Queries are created in MYSQL format and inserted in H2 DB
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MYSQL;
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database=mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate

#to take schema.sql
spring.jpa.defer-datasource-initialization=false

server.port=8081
spring.liquibase.change-log=classpath:db/changelog-master.xml

